apiVersion: v1
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-sc
  resources:
    requests:
      storage: 10Mi
